/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.event.MouseEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author User
 */
public class ClientForm extends javax.swing.JFrame {

    private MouseEvent getPositionEvent;

    private static DataInputStream dataInputStream;
    private static DataOutputStream dataOutputStream;

    private boolean running;

    private String name;
    private int port;

    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form ClientForm
     */
    public ClientForm(Socket clientSocket, String name, int port) {
        initComponents();

        this.name = name;
        this.port = port;

        try {
            dataInputStream = new DataInputStream(clientSocket.getInputStream());
            dataOutputStream = new DataOutputStream(clientSocket.getOutputStream());

            // Send connection message to server
            dataOutputStream.writeUTF("\\connect:" + name);

            addMessageToChat("\n");
            
            clientList.setModel(listModel);

            running = true;

            messageListener();

        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneChat = new javax.swing.JTextPane();
        jScrollPaneClientList = new javax.swing.JScrollPane();
        clientList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanelDragWindow = new javax.swing.JPanel();
        jPanelCloseWindow = new javax.swing.JPanel();
        messageTextField = new javax.swing.JTextField();
        sendMessageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jTextPaneChat.setEditable(false);
        jTextPaneChat.setBorder(null);
        jScrollPane2.setViewportView(jTextPaneChat);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 400, 270);

        jScrollPaneClientList.setViewportView(clientList);

        getContentPane().add(jScrollPaneClientList);
        jScrollPaneClientList.setBounds(410, 60, 80, 270);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 440, 600, 79);

        jPanelDragWindow.setBackground(new java.awt.Color(1, 50, 67));
        jPanelDragWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelDragWindowMouseDragged(evt);
            }
        });
        jPanelDragWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDragWindowMousePressed(evt);
            }
        });

        jPanelCloseWindow.setBackground(new java.awt.Color(228, 241, 254));
        jPanelCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCloseWindowMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDragWindowLayout = new javax.swing.GroupLayout(jPanelDragWindow);
        jPanelDragWindow.setLayout(jPanelDragWindowLayout);
        jPanelDragWindowLayout.setHorizontalGroup(
            jPanelDragWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDragWindowLayout.createSequentialGroup()
                .addGap(0, 447, Short.MAX_VALUE)
                .addComponent(jPanelCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDragWindowLayout.setVerticalGroup(
            jPanelDragWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelDragWindow);
        jPanelDragWindow.setBounds(0, 0, 500, 50);
        getContentPane().add(messageTextField);
        messageTextField.setBounds(10, 350, 390, 20);

        sendMessageButton.setText("Send");
        sendMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendMessageButtonMousePressed(evt);
            }
        });
        getContentPane().add(sendMessageButton);
        sendMessageButton.setBounds(410, 350, 80, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageButtonMousePressed
        String message = messageTextField.getText();

        try {
            if (!message.isEmpty()) {
                dataOutputStream.writeUTF(message);
                messageTextField.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendMessageButtonMousePressed

    private void jPanelCloseWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseWindowMousePressed
        closeClient();
    }//GEN-LAST:event_jPanelCloseWindowMousePressed

    private void jPanelDragWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDragWindowMouseDragged
        // Set new location
        setLocation(evt.getXOnScreen() - getPositionEvent.getX(),
                evt.getYOnScreen() - getPositionEvent.getY());
    }//GEN-LAST:event_jPanelDragWindowMouseDragged

    private void jPanelDragWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDragWindowMousePressed
        // Get current position
        getPositionEvent = evt;
    }//GEN-LAST:event_jPanelDragWindowMousePressed

    public void messageListener() {
        new Thread("Listener") {
            @Override
            public void run() {
                try {
                    while (running) {
                        String message = dataInputStream.readUTF();

                        if (!message.isEmpty()) {
                            if (!isCommand(message)) {
                                addMessageToChat(message);
                            }
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }.start();
    }

    private boolean isCommand(String message) {
        if (message.startsWith("\\connect:")) {

            // Get user name
            String name = message.substring(message.indexOf(":") + 1);

            if (!this.name.equals(name)) {
                addMessageToChat("    User [" + name + "] enter to the chat.");
            }

            return true;

        } else if (message.startsWith("\\disconnect:")) {
            String name = message.substring(message.indexOf(":") + 1);

            addMessageToChat("    User [" + name + "] exit from the chat.");

            return true;
        } else if(message.startsWith("\\userlist:")) {
            String[] users = message.split(":");
            
            listModel.clear();
            for(int i = 1; i < users.length; i++) {
                addToList(users[i]);
            }
            
            return true;
        }

        return false;
    }

    private void addMessageToChat(String message) {
        // Add message to log panel
        jTextPaneChat.setText(jTextPaneChat.getText().concat(message + "\n"));
    }
    
    // Add name to list
    public void addToList(String name) {
        listModel.addElement(name);
    }

    // Close client
    private void closeClient() {

        try {
            // Stop thread lopp
            running = false;

            // Send disconnection message to server
            dataOutputStream.writeUTF("\\disconnect:" + name);

            // Close window
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm(null, null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> clientList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelDragWindow;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneClientList;
    private static javax.swing.JTextPane jTextPaneChat;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton sendMessageButton;
    // End of variables declaration//GEN-END:variables
}
